name: School Management System API

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup ASP.NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.10.x
      
      - name: Install Dependencies
        run: dotnet restore ./SchoolManagement.Api/SchoolManagement.Api.csproj
      
      - name: Build
        run: dotnet build ./SchoolManagement.Api/SchoolManagement.Api.csproj --configuration Release --no-restore