name: Build and deploy .NET Core application to Web App School-Management
on:
  push:
    branches:
    - main
env:
  AZURE_WEBAPP_NAME: School-Management
  AZURE_WEBAPP_PACKAGE_PATH: SchoolManagement.Api/publish
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: SchoolManagement.Api
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Deploy to MonsterASP
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.MONSTERASP_FTP_HOST }}
        username: ${{ secrets.MONSTERASP_FTP_USERNAME }}
        password: ${{ secrets.MONSTERASP_FTP_PASSWORD }}
        local-dir: ./publish/
        git-ftp-args: --insecure
